# Usa a imagem oficial do MySQL
FROM mysql:8.0

# Define variáveis de ambiente para configurar o MySQL
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=formulario_clientes
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=1234
# Copia o arquivo de inicialização SQL para o diretório de inicialização do MySQL


# Exponha a porta padrão do MySQL
EXPOSE 3306